version: "3.9"

services:
  backend:
    image: backend:latest
    container_name: boardgame-backend
    ports:
      - "1234:1234"
    environment:
      - PORT=1234
    restart: unless-stopped

  frontend:
    image: game:latest
    container_name: boardgame-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
